
// action type of categories
export const GET_CATEGORIES = "GET_CATEGORIES";
export const GET_CATEGORIES_SUCCESS = "GET_CATEGORIES_SUCCESS";
export const GET_CATEGORIES_FAILURE = "GET_CATEGORIES_FAILURE";

export const ADD_CATEGORIES_REQUEST = "ADD_CATEGORIES_REQUEST";
export const ADD_CATEGORIES_REQUEST_SUCCESS = "ADD_CATEGORIES_REQUEST_SUCCESS";
export const ADD_CATEGORIES_REQUEST_FAILURE = "ADD_CATEGORIES_REQUEST_FAILURE";

export const UPDATE_CATEGORIES_REQUEST = "UPDATE_CATEGORIES_REQUEST";
export const UPDATE_CATEGORIES_REQUEST_SUCCESS =
  "UPDATE_CATEGORIES_REQUEST_SUCCESS";
export const UPDATE_CATEGORIES_REQUEST_FAILURE =
  "UPDATE_CATEGORIES_REQUEST_FAILURE";

export const REMOVE_CATEGORIES = "REMOVE_CATEGORIES";
export const REMOVE_CATEGORIES_SUCCESS = "REMOVE_CATEGORIES_SUCCESS";
export const REMOVE_CATEGORIES_FAILURE = "REMOVE_CATEGORIES_FAILURE";

// action type of New tire rework

export const GET_NEWTIREDATA ="GET_NEWTIREDATA";
export const GET_NEWTIREDATA_SUCCESS = "GET_NEWTIREDATA_SUCCESS";
export const GET_NEWTIREDATA_FAILURE = "GET_NEWTIREDATA_FAILURE";


export const ADD_NEWTIREDATA_REQUEST = "ADD_CATEGORIES_REQUEST";
export const ADD_NEWTIREDATA_REQUEST_SUCCESS = "ADD_CATEGORIES_REQUEST_SUCCESS";
export const ADD_NEWTIREDATA_REQUEST_FAILURE = "ADD_CATEGORIES_REQUEST_FAILURE";

export const UPDATE_NEWTIREDATA_REQUEST = "UPDATE_CATEGORIES_REQUEST";
export const UPDATE_NEWTIREDATA_REQUEST_SUCCESS =
  "UPDATE_CATEGORIES_REQUEST_SUCCESS";
export const UPDATE_NEWTIREDATA_REQUEST_FAILURE =
  "UPDATE_CATEGORIES_REQUEST_FAILURE";

export const REMOVE_NEWTIREDATA = "REMOVE_CATEGORIES";
export const REMOVE_NEWTIREDATA_SUCCESS = "REMOVE_CATEGORIES_SUCCESS";
export const REMOVE_NEWTIREDATA_FAILURE = "REMOVE_CATEGORIES_FAILURE";


